import keyMirror from 'keymirror'

export default keyMirror({
  API_FAILURE: null,
  API_REQUEST: null,
  API_SUCCESS: null,

  AUTH_LOGIN_FAILURE: null,
  AUTH_LOGIN_REQUEST: null,
  AUTH_LOGIN_SUCCESS: null,
  AUTH_LOGOUT: null,
  AUTH_TOKEN_EXPIRED_OR_INVALID: null,

  DRAWER_COLLAPSE_ALL: null,
  DRAWER_TOGGLE_NAVIGATION: null,
  DRAWER_TOGGLE_SIDEBAR: null,

  PAGE_CREATE_FAILURE: null,
  PAGE_CREATE_REQUEST: null,
  PAGE_CREATE_SUCCESS: null,

  PAGE_EDIT_FAILURE: null,
  PAGE_EDIT_REQUEST: null,
  PAGE_EDIT_SUCCESS: null,

  PAGE_FAILURE: null,
  PAGE_REQUEST: null,
  PAGE_SUCCESS: null,

  PAGINATED_LIST_FAILURE: null,
  PAGINATED_LIST_REQUEST: null,
  PAGINATED_LIST_SUCCESS: null,
})
