import keyMirror from 'keymirror'

export default keyMirror({
  API_FAILURE: null,
  API_REQUEST: null,
  API_SUCCESS: null,

  AUTH_LOGIN_FAILURE: null,
  AUTH_LOGIN_REQUEST: null,
  AUTH_LOGIN_SUCCESS: null,
  AUTH_LOGOUT: null,
  AUTH_REGISTER_FAILURE: null,
  AUTH_REGISTER_REQUEST: null,
  AUTH_REGISTER_SUCCESS: null,
  AUTH_TOKEN_EXPIRED_OR_INVALID: null,

  CHANGE_PROFILE_FAILURE: null,
  CHANGE_PROFILE_REQUEST: null,
  CHANGE_PROFILE_SUCCESS: null,

  DRAWER_COLLAPSE_ALL: null,
  DRAWER_TOGGLE_NAVIGATION: null,
  DRAWER_TOGGLE_SIDEBAR: null,

  FLASH_ADD_MESSAGE: null,
  FLASH_REMOVE_ALL_MESSAGES: null,
  FLASH_REMOVE_MESSAGE: null,

  INFINITE_LIST_FAILURE: null,
  INFINITE_LIST_INITIALIZE: null,
  INFINITE_LIST_REQUEST: null,
  INFINITE_LIST_SUCCESS: null,

  META_FAILURE: null,
  META_REQUEST: null,
  META_SUCCESS: null,

  PAGE_FAILURE: null,
  PAGE_REQUEST: null,
  PAGE_SUCCESS: null,

  PAGINATED_LIST_FAILURE: null,
  PAGINATED_LIST_REMOVE_ITEM: null,
  PAGINATED_LIST_REQUEST: null,
  PAGINATED_LIST_SUCCESS: null,

  REDIRECT: null,

  RESET_PASSWORD_FAILURE: null,
  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,

  RESOURCE_CREATE_FAILURE: null,
  RESOURCE_CREATE_REQUEST: null,
  RESOURCE_CREATE_SUCCESS: null,
  RESOURCE_DELETE_FAILURE: null,
  RESOURCE_DELETE_REQUEST: null,
  RESOURCE_DELETE_SUCCESS: null,
  RESOURCE_FAILURE: null,
  RESOURCE_REQUEST: null,
  RESOURCE_SUCCESS: null,
  RESOURCE_UPDATE_FAILURE: null,
  RESOURCE_UPDATE_REQUEST: null,
  RESOURCE_UPDATE_SUCCESS: null,

  SLOTS_FAILURE: null,
  SLOTS_REQUEST: null,
  SLOTS_SUCCESS: null,

  TICKET_FAILURE: null,
  TICKET_REQUEST: null,
  TICKET_SUCCESS: null,
})
