import keyMirror from 'keymirror'

export default keyMirror({
  API_FAILURE: null,
  API_REQUEST: null,
  API_SUCCESS: null,

  AUTH_LOGIN_FAILURE: null,
  AUTH_LOGIN_REQUEST: null,
  AUTH_LOGIN_SUCCESS: null,
  AUTH_LOGOUT: null,
  AUTH_REGISTER_FAILURE: null,
  AUTH_REGISTER_REQUEST: null,
  AUTH_REGISTER_SUCCESS: null,
  AUTH_TOKEN_EXPIRED_OR_INVALID: null,

  DRAWER_COLLAPSE_ALL: null,
  DRAWER_TOGGLE_NAVIGATION: null,
  DRAWER_TOGGLE_SIDEBAR: null,

  FLASH_ADD_MESSAGE: null,
  FLASH_REMOVE_ALL_MESSAGES: null,
  FLASH_REMOVE_MESSAGE: null,

  PAGE_FAILURE: null,
  PAGE_REQUEST: null,
  PAGE_SUCCESS: null,

  PAGINATED_LIST_FAILURE: null,
  PAGINATED_LIST_REMOVE_ITEM: null,
  PAGINATED_LIST_REQUEST: null,
  PAGINATED_LIST_SUCCESS: null,

  RESOURCE_CREATE_FAILURE: null,
  RESOURCE_CREATE_REQUEST: null,
  RESOURCE_CREATE_SUCCESS: null,
  RESOURCE_DELETE_FAILURE: null,
  RESOURCE_DELETE_REQUEST: null,
  RESOURCE_DELETE_SUCCESS: null,
  RESOURCE_FAILURE: null,
  RESOURCE_REQUEST: null,
  RESOURCE_SUCCESS: null,
  RESOURCE_UPDATE_FAILURE: null,
  RESOURCE_UPDATE_REQUEST: null,
  RESOURCE_UPDATE_SUCCESS: null,
})
